[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["src/**", "Cargo.toml", "Cargo.lock", "config/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
